languages = {'ru': {
				'code': 'ru',
				'font': 'fonts/onestrokescriptrus_lat.otf',
				'short_weekdays': ('вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'),
				'full_weekdays': ('понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'),
				'months': ('январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'),
				'menu_buttons': ('Календарь', 'Статистика', 'Использование', 'Настройки'),
				'periods': ('за всё время', 'за год', 'за полгода', 'за месяц'),
				'total': 'Всего',
				'this_year': 'В этом году',
				'this_month': 'В этом месяце',
				'last_month': 'В прошлом месяце',
				'month_average': 'Средне в месяц',
				'month_efficiency': 'Эффективность в этом месяце',
				'close': 'Закрыть',
				'language': 'Язык',
				'theme': 'Тема',
				'roman_numerals': 'Римские цифры',
				'girl': 'Тян',
				'check_count': 'Кол-во заметок в день',
				'delete_data': 'Сбросить данные',
				'new_calendar': 'Новый календарь'
			},
			'en': {
				'code': 'en',
				'font': 'fonts/onestrokescriptrus_lat.otf',
				'short_weekdays': ('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'),
				'full_weekdays': ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'),
				'months': ('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'),
				'menu_buttons': ('Calendar', 'Statistics', 'Usage', 'Settings'),
				'periods': ('All Time', 'This Year', 'Last Six Months', 'This Month'),
				'total': 'Total',
				'this_year': 'This Year',
				'this_month': 'This Month',
				'last_month': 'Last Month',
				'month_average': 'Month Average',
				'month_efficiency': 'Month Efficiency',
				'close': 'Close',
				'language': 'Language',
				'theme': 'Theme',
				'roman_numerals': 'Roman Numerals',
				'girl': 'Chan',
				'check_count': 'Daily Check Count',
				'delete_data': 'Delete Data',
				'new_calendar': 'New Calendar' 
			},
			'de': {
				'code': 'de',
				'font': 'fonts/onestrokescriptrus_lat.otf',
				'short_weekdays': ('So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'),
				'full_weekdays': ('Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'),
				'months': ('Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'),
				'menu_buttons': ('Kalender', 'Statistik', 'Nutzung', 'Einstellungen'),
				'periods': ('für alle Zeiten', 'für das Jahr', 'für ein halbes Jahr', 'für den Monat'),
				'total': 'Insgesamt',
				'this_year': 'In diesem Jahr',
				'this_month': 'In diesem Monat',
				'last_month': 'Im letzten Monat',
				'month_efficiency': 'Monatseffizienz',
				'month_average': 'Monatsdurchschnitt',
				'close': 'Schließen',
				'language': 'Sprache',
				'theme': 'Thema',
				'roman_numerals': 'Römische Zahlen',
				'girl': 'Mädchen',
				'check_count': 'Tägliche Scheckanzahl',
				'delete_data': 'Daten löschen',
				'new_calendar': 'Neuer Kalenar'
			},
			'es': {
				'code': 'es',
				'font': 'fonts/onestrokescriptrus_lat.otf',
				'short_weekdays': ('dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'),
				'full_weekdays': ('domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'),
				'months': ('enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'),
				'menu_buttons': ('Calendario', 'Estadísticas', 'Uso', 'Configuraciones'),
				'periods': ('Todo el tiempo', 'Este año', 'Últimos seis meses', 'Este mes'),
				'total': 'Total',
				'this_year': 'Este año',
				'this_month': 'Este mes',
				'last_month': 'El mes pasado',
				'month_average': 'Promedio mensual',
				'month_efficiency': 'Eficiencia mensual',
				'close': 'Cerrar',
				'language': 'Idioma',
				'theme': 'Tema',
				'roman_numerals': 'Números romanos',
				'girl': 'Chica',
				'check_count': 'Recuento diario de cheques',
				'delete_data': 'Eliminar datos',
				'new_calendar': 'Nuevo calendario'
			},
			'pl': {
				'code': 'pl',
				'font': 'fonts/polish.ttf',
				'short_weekdays': ('niedz', 'pon', 'wt', 'śr', 'cz', 'pt', 'sob'),
				'full_weekdays': ('niedziela', 'poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota'),
				'months': ('styczeń', 'luty', 'marzec', 'kwiecień', 'maj', 'czerwiec', 'lipiec', 'sierpień', 'wrzesień', 'październik', 'listopad', 'grudzień'),
				'menu_buttons': ('Kalendarz', 'Statystyki', 'Użycie', 'Ustawienia'),
				'periods': ('Wszystko', 'W tym roku', 'Ostatnie sześć miesięcy', 'W tym miesiącu'),
				'total': 'Razem',
				'this_year': 'W tym roku',
				'this_month': 'W tym miesiącu',
				'last_month': 'W zeszłym miesiącu',
				'month_average': 'średnia miesięczna',
				'month_efficiency': 'Wydajność miesiąca',
				'close': 'Zamknij',
				'language': 'Język',
				'theme': 'Motyw',
				'roman_numerals': 'Liczby rzymskie',
				'girl': 'Dziewczyna',
				'check_count': 'Dzienna liczba czeków',
				'delete_data': 'Usuń dane',
				'new_calendar': 'Nowy kalendarz'
			},
			'ja': {
				'code': 'ja',
				'font': 'fonts/japanese.otf',
				'short_weekdays': ("日", "月", "火", "水", "木", "金", "土"),
				'full_weekdays':('月曜日','火曜日','水曜日','木曜日','金曜日','土曜日','日曜日'),
				'months':('1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'),
				'menu_buttons':('カレンダー','統計','使用','設定'),
				'periods':('すべての時間','年','6ヶ月','月'),
				'total':'合計',
				'this_year':'今年',
				'this_month':'今月',
				'last_month':'先月',
				'month_average': '月平均',
				'month_efficiency': '月の効率',
				'close':'閉じる',
				'language':'言語',
				'theme':'テーマ',
				'roman_numerals':'ローマ数字',
				'女の子':'ちゃん',
				'girl': 'チャン',
				'check_count': '毎日のチェック数',
				'delete_data':'データのリセット',
				'new_calendar': '新しいカレンダー'
			},
			'am': {
				'code': 'am',
				'font': 'fonts/washrab.ttf',
				'short_weekdays': ('እሑድ', 'ሰኞ', 'ማክሰኞ', 'ረቡዕ', 'ሐሙስ', 'አርብ', 'ቅዳሜ'),
				'full_weekdays': ('ሰኑይ', 'ሰኞ', 'ማክሰኞ', 'ረቡዕ', 'ሐሙስ', 'አርብ', 'ቅዳሜ'),
				'months': ('ጃንዩወሪ', 'ፌብሩወሪ', 'ማርች', 'ኤፕሪል', 'ሜይ', 'ጁን', 'ጁላይ', 'ኦገስት', 'ሴፕቴምበር', 'ኦክቶበር', 'ኖቬምበር', 'ዲሴምበር'),
				'menu_buttons': ('ቀን መዝገብ', 'ስታትስቲክ', 'እንቅስቃሴ', 'ቅንብር'),
				'periods': ('ሁሉም ጊዜ', 'ይህ ዓመት', 'ያለፉት ስድስት ወራት', 'ይህ ወር'),
				'total': 'ጠቅላላ',
				'this_year': 'ይህ ዓመት',
				'this_month': 'ይህ ወር',
				'last_month': 'ያለፉት ወር',
				'month_average': 'ወር አማካይ',
				'month_efficiency': 'ወር ውጤታማነት',
				'close': 'ዝጋ',
				'language': 'ቋንቋ',
				'theme': 'ጥቅስ',
				'roman_numerals': 'ሮማዊ ቁጥሮች',
				'girl': 'ወንድም',
				'check_count': 'ዕለታዊ ቼክ ቆጠራ',
				'delete_data': 'ውስጥ ይወድቃል',
				'new_calendar': 'ኒው ካሌዶኒያ'
			},
			'cu': {
				'code': 'cu',
				'font': 'fonts/slavic.otf',
				'short_weekdays': ('всъ', 'пнъ', 'втъ', 'сръ', 'чтъ', 'птъ', 'сбъ'),
				'full_weekdays': ('понедѣльникъ', 'вторникъ', 'срѣда', 'четвергъ', 'пѧтница', 'сѫббѡта', 'воскресеньѥ'),
				'months': ('ꙗнварь', 'февраль', 'мартъ', 'ꙗпрель', 'маи', 'їюнь', 'їюль', 'яигѫст', 'сентѧбрь', 'ѻктябрь', 'ноꙗбрь', 'декабрь'),
				'menu_buttons': ('Календарь', 'Статистика', 'Испольꙁованиѥ', 'Настроикꙑ'),
				'periods': ('ꙁа все врѣмѧ', 'ꙁа годъ', 'ꙁа полгода', 'ꙁа мѣсѧцъ'),
				'total': 'Всего',
				'this_year': 'Въ ѥтом годоу',
				'this_month': 'Въ ѥтом мѣсѧцѣ',
				'last_month': 'Въ прошломъ мѣсѧцѣ',
				'month_average': 'Срѣдне въ мѣсѧцъ',
				'month_efficiency': 'ѥффективность въ ѥтомъ мѣсѧцѣ',
				'close': 'ꙁакрꙑть',
				'language': 'ѩꙁꙑк',
				'theme': 'Тѣма',
				'roman_numerals': 'Римскꙑѥ цифрꙑ',
				'girl': 'Тѧнъ',
				'check_count': 'Колъ-во ꙁаметок въ день',
				'delete_data': 'Сбросить даннꙑѥ',
				'new_calendar': 'новꙑи календарь'
			},
			'la': {
				'code': 'la',
				'font': 'fonts/latin.ttf',
				'short_weekdays': ('Sol', 'Lun', 'Mar', 'Mer', 'Jov', 'Ven', 'Sat'),
				'full_weekdays': ('Lunae', 'Martis', 'Mercurii', 'Iovis', 'veneris', 'Saturni', 'Dominica'),
				'months': ('Ianuarius', 'Februarius', 'Martius', 'Aprilis', 'Maius', 'Iunius', 'Iulius', 'Augustus', 'September', 'October', 'November', 'December'),
				'menu_buttons': ('Calendarium', 'Statistica', 'Usus', 'Occasus'),
				'periods': ('Omni Tempore', 'Hoc Anno', 'Novissimis Sex Mensibus', 'Hoc Mense'),
				'total': 'Total',
				'this_year': 'Hoc Anno',
				'this_month': 'Hoc Mense',
				'last_month': 'Praeterito Mense',
				'month_average': 'Mensis Mediocris',
				'month_efficiency': 'Mensis Efficientiam',
				'close': 'Claudere',
				'language': 'Lingua',
				'theme': 'Thema',
				'roman_numerals': 'Numeri Romani',
				'girl': 'Puella',
				'check_count': 'Quotidie Reprehendo Comitem',
				'delete_data': 'Delere Data',
				'new_calendar': 'Calendarium novum'
			},
			'???': {
				'code': '???',
				'font': 'fonts/minecraft-enchantment.ttf',
				'short_weekdays': ('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'),
				'full_weekdays': ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'),
				'months': ('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'),
				'menu_buttons': ('Calendar', 'Statistics', 'Usage', 'Settings'),
				'periods': ('All Time', 'This Year', 'Last Six Months', 'This Month'),
				'total': 'Total',
				'this_year': 'This Year',
				'this_month': 'This Month',
				'last_month': 'Last Month',
				'month_average': 'Month Average',
				'month_efficiency': 'Month Efficiency',
				'close': 'Close',
				'language': 'Language',
				'theme': 'Theme',
				'roman_numerals': 'Roman Numerals',
				'girl': 'Girl',
				'check_count': 'Daily Check Count',
				'delete_data': 'Delete Data',
				'new_calendar': 'New Calendar'
			}
}